app:
  name: app-rs
  version: 1.0.0
  port: ${port:38080}
  url: ${app-url:http://localhost}:${app.port}
  log:
    path: ./logs/logback.log



server:
  port: ${app.port}


spring:
  profiles:
    active: local
  pid:
    file: ${app.name}.pid

  # ===================================================================================================================================
  # Database 설정
  # ===================================================================================================================================
  h2:
    console:
      enabled: true
      path: /${app.name}-db
  sql:
    init:
      mode: always
      platform: h2
  datasource:
#    url: jdbc:h2:file:./data${spring.h2.console.path};FILE_LOCK=NO
    url: jdbc:h2:file:./data${spring.h2.console.path};AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password: rs
  hikari:
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true



# ==================================================================================================================
# spring-doc 설정
# ==================================================================================================================
springdoc:
  #show-actuator: true
  #show-login-endpoint: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha #alpha/method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    csrf:
      enabled: false


# =====================================================
# Logging ??
# =====================================================
logging:
  charset:
    console: utf-8
    file: utf-8
  file:
    name: ${app.log.path}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-history: 30
      max-file-size:
        100MB
  level:
    root: info
    '[org.hibernate.sql]': debug
#    '[org.hibernate.jpa]': debug
    '[org.springframework.orm.jpa]': debug